name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t jelajahmedika/project .
      - name: Publish image to docker hub
        run: docker push jelajahmedika/project:latest   

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: sudo docker pull jelajahmedika/project:latest
      - name: Delete Old Container
        run: sudo docker rm -f jelajahMedikaWebAppContainer
      - name: Run docker container
        run: sudo docker run -d --add-host=host.docker.internal:host-gateway -p 5000:5000 --name jelajahMedikaWebAppContainer jelajahmedika/project
      - name: Delete Not Associate Image
        run: sudo docker image prune -af